config/routes.rb
ReworkDemo::Application.routes.draw do

  resources :home do
       collection do
        get 'linkedin_demo_for_eesamohammed'
        post 'fetch_linked_in_details'
        
        post 'fetch_linked_in_details_for_eesa'
      end
  end
   root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
		
		def index
				#~ @profile = Linkedin::Profile.get_profile("http://www.linkedin.com/in/udhayakumars")
				@profile = Linkedin::Profile.get_profile("http://www.linkedin.com/pub/shane-rasnak/13/4a4/53")
		end
		
			def linkedin_demo_for_eesamohammed
				#~ @profile = Linkedin::Profile.get_profile("http://www.linkedin.com/in/udhayakumars")
				@profile = Linkedin::Profile.get_profile("http://www.linkedin.com/in/eesamohammed")
		end
		
		def fetch_linked_in_details_for_eesa
				l_uri = params[:link_in_url].gsub("https","http")
				@profile = Linkedin::Profile.get_profile(l_uri)
				#~ @profile = Linkedin::Profile.get_profile(params[:link_in_url])
				Emailer.check_email(params[:link_in_url],"from eesamohammed").deliver if Rails.env == "production"
		end		
		
		def fetch_linked_in_details
				l_uri = params[:link_in_url].gsub("https","http")
				@profile = Linkedin::Profile.get_profile(l_uri)
				#~ @profile = Linkedin::Profile.get_profile(params[:link_in_url])
				Emailer.check_email(params[:link_in_url],"from rework, mauri").deliver if Rails.env == "production"
		end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_user_info.html.erb
<%if profile.blank?%>
<div style="font-size: 20px;margin-top: 90px;text-align: center;">The URL which you provided is not available to fetch data</div>
<%else%>
<style>
label
{
color: #000000;
    font-size: 17px !important;
}

</style>
<div style="border:0px solid;float:left;width:45%; padding: 20px;">
<p>
    <label for="first_name_title">First Name: </label><br>
    <input type="text" name="first_name" id="first_name" value="<%=profile.first_name%>" size="50">
</p>
</br>
<p>
    <label for="last_name_title">Last Name: </label><br>
    <input type="text" name="last_name" id="last_name" value="<%=profile.last_name%>" size="50">
</p>
</br>
<p>
    <label for="name_title">Name: </label><br>
    <input type="text" name="name" id="name" value="<%=profile.name%>" size="50">
</p>
</br>
<p>
    <label for="location_title">Location: </label><br>
    <input type="text" name="location" id="location" value="<%=profile.location%>" size="50">
</p>
</br>
<p>
    <label for="country_title">Country: </label><br>
    <input type="text" name="country" id="country" value="<%=profile.country%>" size="50">
</p>
</br>
<p>
    <label for="industry_title">Industry: </label><br>
    <input type="text" name="industry" id="industry" value="<%=profile.industry%>" size="50">
</p>
</br>

<p>
    <label for="skills_title">Skills: </label><br>
    <textarea type="text" style="width: 522px;min-height:300px" id="skills"><%=profile.skills.blank? ? "" :  profile.skills.join(",")%></textarea>
</p>
</br>

</div>
<div style="border:0px solid;float:left;width:45%; padding: 20px;">
<p>
    <label for="image_title">Image: </label><br>
    <img src="<%=profile.picture.blank? ? "/assets/no-asset.jpg" : profile.picture%>" style="width:100;height:100px" >
</p>
 
			<p style="padding-top:30px">
    <label for="education_title">Education: </label><br>
				<%if !profile.education.blank?%>
				<%profile.education.each do |p_e|%>
				<%#=p_e%>
    <div style="float:left"><input type="text" value="<%=p_e[:name]%>">&nbsp<input type="text" value="<%=p_e[:description]%>" >&nbsp<input type="text" value="<%=p_e[:period]%>"></div></br>
				
				<%end%>
				<%else%>
								Not able to Fetch/Not Available
				<%end%>
</p>
 
			<p style="padding-top:30px">
    <label for="certifications_title">Certifications: </label><br>
				<%if !profile.certifications.blank?%>
				<%profile.certifications.each do |cert|%>
				<%#=p_e%>
    <div style="float:left"><input type="text" value="<%=cert[:name]%>" size="32">&nbsp<input type="text" value="<%=cert[:autority]%>" size="32"></div></br>
				<%end%>
				<%else%>
								Not able to Fetch/Not Available
				<%end%>
</p>
 
		<p style="padding-top:30px">
    <label for="current_companies_title">Current Company: </label><br>
				<%if !profile.current_companies.blank?%>
				<%profile.current_companies.each do |cur_comp|%>
				<%#=p_e%>
    <div style="float:left"><input type="text" value="<%=cur_comp[:title]%>">&nbsp<input type="text" value="<%=cur_comp[:company]%>">&nbsp<input type="text" value="<%=cur_comp[:website]%>"></div></br>
				
				<%end%>
				<%else%>
								Not able to Fetch/Not Available
				<%end%>
</p>
 

		<p style="padding-top:30px">
    <label for="past_companies_title">Previous Employments: </label><br>
				<%if !profile.past_companies.blank?%>
				<%profile.past_companies.each do |pas_comp|%>
				<%#=p_e%>
    <div style="float:left"><input type="text" value="<%=pas_comp[:title]%>">&nbsp<input type="text" value="<%=pas_comp[:company]%>">&nbsp<input type="text" value="<%=pas_comp[:website]%>"></div></br>
				<%end%>
				<%else%>
								Not able to Fetch/Not Available
				<%end%>
</p>
 </br>
		<p style="margin-top: 40px;">
    <label for="groups_title">Groups: </label><br>
				<%if !profile.groups.blank?%>
				<%profile.groups.each do |group|%>
				<%#=p_e%>
    <div style="float:left"><input type="text" value="<%=group[:name]%>">&nbsp<input type="text" value="<%=group[:link]%>" size="45"></div></br>
				<%end%>
				<%else%>
								Not able to Fetch/Not Available
				<%end%>
</p>
</br>
				

 
  </div>
		
		
		<script>
		$('#skills').tagsInput({width:'500px',height:'250px','defaultText':''});
		</script>
		<%end%>

app/views/home/fetch_linked_in_details.js.erb
$("#user_contents").html('<%=  escape_javascript(render :partial => "user_info.html" , :locals => {:profile => @profile }) %>')
 

app/views/home/fetch_linked_in_details_for_eesa.js.erb
$("#user_contents").html('<%=  escape_javascript(render :partial => "user_info.html" , :locals => {:profile => @profile }) %>')
 

app/views/home/index.html.erb
<style>
#main_button
{
 -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background: -moz-linear-gradient(-90deg, #838A90, #414549) repeat scroll 0 0 rgba(0, 0, 0, 0);
    border-color: #616A71 #484E53 #363B3F;
    border-image: none;
    border-radius: 200px;
    border-style: solid;
    border-width: 1px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1), 0 1px 0 0 rgba(255, 255, 255, 0.2) inset;
    color: #EFEFEF;
    cursor: pointer;
    display: inline-block;
    font-family: Helvetica,Arial,sans-serif;
    font-size: 1em;
    font-weight: bold;
    line-height: 12px;
    margin-right: 3px;
    padding: 7px 16px 6px;
    text-decoration: none;
    text-shadow: 0 1px 0 #000000;
				}
</style>
 

<div class="panel" style=" position: absolute;width: 92%;padding:50px">
<div class="panel_contents">

<div style="text-align:center; padding: 20px;">
Enter the linkedIn URI to fetch data</br>
<input type="text"  id="full_uri" size="100px" value="https://www.linkedin.com/pub/shane-rasnak/13/4a4/53"></br>
EG: https://www.linkedin.com/in/udhayakumars</br>
EG: https://www.linkedin.com/pub/evan-walden/10/ab7/110</br>
EG: https://www.linkedin.com/in/abetaleb</br>
EG: https://www.linkedin.com/pub/ashley-elmblad/5/340/689</br>
<input type="button" id="main_button" value="Get Details">
</div>

<div id="user_contents" style="border:0px solid;min-height:200px;height:auto;">
<%if !@profile.blank?%>
  <%= render :partial => "user_info.html" , :locals => {:profile => @profile } %>
<%end%>
<div>

</div>
</div>
 

<div style="padding-bottom:50px"></div>







<script>

$('#main_button').click(function () {
 $("#user_contents").html("")
$("#user_contents").html('<div style="text-align:center"><img src="/assets/loading.gif"></div>')
										$.ajax({
														type: "POST",
														url: "<%=fetch_linked_in_details_home_index_path%>",
														data: { 
														link_in_url: 		 $("#full_uri").val()
														}
												}).done(function( msg ) {
														// Success
												});
       });
</script>

app/views/home/linkedin_demo_for_eesamohammed.html.erb
<style>
#main_button
{
 -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    background: -moz-linear-gradient(-90deg, #838A90, #414549) repeat scroll 0 0 rgba(0, 0, 0, 0);
    border-color: #616A71 #484E53 #363B3F;
    border-image: none;
    border-radius: 200px;
    border-style: solid;
    border-width: 1px;
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1), 0 1px 0 0 rgba(255, 255, 255, 0.2) inset;
    color: #EFEFEF;
    cursor: pointer;
    display: inline-block;
    font-family: Helvetica,Arial,sans-serif;
    font-size: 1em;
    font-weight: bold;
    line-height: 12px;
    margin-right: 3px;
    padding: 7px 16px 6px;
    text-decoration: none;
    text-shadow: 0 1px 0 #000000;
				}
</style>
 

<div class="panel" style=" position: absolute;width: 92%;padding:50px">
<div class="panel_contents">

<div style="text-align:center; padding: 20px;">
Enter the linkedIn URI to fetch data</br>
<input type="text"  id="full_uri" size="100px" value="https://www.linkedin.com/in/eesamohammed"></br>
EG: https://www.linkedin.com/in/udhayakumars</br>
 
<input type="button" id="main_button" value="Get Details">
</div>

<div id="user_contents" style="border:0px solid;min-height:200px;height:auto;">
<%if !@profile.blank?%>
  <%= render :partial => "user_info.html" , :locals => {:profile => @profile } %>
<%end%>
<div>

</div>
</div>
 

<div style="padding-bottom:50px"></div>







<script>

$('#main_button').click(function () {
 $("#user_contents").html("")
$("#user_contents").html('<div style="text-align:center"><img src="/assets/loading.gif"></div>')
										$.ajax({
														type: "POST",
														url: "<%=fetch_linked_in_details_for_eesa_home_index_path%>",
														data: { 
														link_in_url: 		 $("#full_uri").val()
														}
												}).done(function( msg ) {
														// Success
												});
       });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<link href="/admin_style.css" media="all" rel="stylesheet" type="text/css" />
<body style="background-color:white" class="active_admin">
<div id="header" class="header">
        <h1 id="site_title" class="site_title">WorkDemo</h1>
        <ul id="tabs" class="header-item">
<!--          <li id="home" class=""><a href="/admin/home">Home</a></li>-->
        </ul>
        <p id="utility_nav" class="header-item"></p>
								
								
					 
		</div>

<%=yield%>

</body>
</html>